FROM rabbitmq:3.6.10-management

LABEL maintainer="Octavian Ionescu<itavyg@gmail.com>"

COPY rabbitmq.config /etc/rabbitmq/rabbitmq.config
# mqconnuser:mqconnpwd
COPY definitions.json /etc/rabbitmq/definitions.json
